
version: "3"
services:
  backend_dev:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./backend/src:/app"
    tty: true

  frontend_dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - "./frontend:/app"
    tty: true

  postgres:
    image: postgres
    restart: always
    environment:
        POSTGRES_PASSWORD: "haev2uavefoR2Daequ6iequ4ung7vah3"
